# Generated by Django 3.2.3 on 2021-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageLocation', models.CharField(max_length=100)),
                ('submittedBy', models.CharField(max_length=200)),
            ],
        ),
    ]
