# Generated by Django 3.2.5 on 2021-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='businessCardImages')),
                ('submittedBy', models.CharField(max_length=200)),
                ('submittedDate', models.DateField()),
                ('isProcessed', models.CharField(max_length=1)),
            ],
        ),
    ]
