# Generated by Django 3.2.3 on 2021-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadBusinessCard', '0002_auto_20210617_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='imageLocation',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='image',
            field=models.FileField(null=True, upload_to='businessCardImages'),
        ),
    ]
