# Generated by Django 3.2.3 on 2021-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadBusinessCard', '0003_auto_20210617_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='image',
            field=models.ImageField(null=True, upload_to='businessCardImages'),
        ),
    ]
