# Generated by Django 3.2.3 on 2021-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=300)),
                ('contactOrganization', models.CharField(max_length=200)),
                ('contactEmail', models.EmailField(max_length=100)),
                ('contactPhoneNumber', models.CharField(max_length=20)),
                ('contactCardInfo', models.CharField(max_length=1000)),
            ],
        ),
    ]
