# Generated by Django 3.2.5 on 2021-08-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessContacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontact',
            name='contactCardId',
        ),
    ]
