# Generated by Django 3.2.5 on 2021-07-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessContacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='BusinessContact',
        ),
    ]
